apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: setusername
  namespace: setns
rules:
- apiGroups: [""]
  resources:
  - pods
  - pods/log
  - deployment
 #resourceNames: ["setdeploy"]
  verbs: ["get", "list", "watch"]
