apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: setusername-rolebinding
  namespace: setns  
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: setusername
subjects:
- kind: User
  name: setusername
  namespace: setns
