apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: setusername-role
  namespace: setns
rules:
- apiGroups: [""]
  resources:
  - pods
  - pods/log
  - deployment
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources:
  - pods/exec
 #resourceNames: ["setdeploy"]
  verbs:
  - create
- apiGroups:
  - extensions
  - apps
  resources:
  - deployments
  - deployments/logs
 #resourceNames: ["setdeploy"]
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - extensions
  - apps
  resources:
  - deployments
  - deployments/logs
 #resourceNames: ["setdeploy"]
  verbs:
  - get
  - list
  - watch